from typing import Protocol, Optional, List, Dict, Any
from core.contracts import Document, Entity, Event, Problem, Evidence, Provenance

class DocumentStore(Protocol):
    async def save_document(self, document: Document) -> None: ...
    async def get_document(self, document_id: str) -> Optional[Document]: ...
    async def list_documents(self, limit: int = 100, offset: int = 0) -> List[Document]: ...

class EntityStore(Protocol):
    async def save_entity(self, entity: Entity) -> None: ...
    async def get_entity(self, entity_id: str) -> Optional[Entity]: ...
    async def search_entities(self, query: str) -> List[Entity]: ...

class EventStore(Protocol):
    async def save_event(self, event: Event) -> None: ...
    async def get_event(self, event_id: str) -> Optional[Event]: ...
    async def list_events_for_actor(self, actor_id: str) -> List[Event]: ...

class ProblemStore(Protocol):
    async def save_problem(self, problem: Problem) -> None: ...
    async def get_problem(self, problem_id: str) -> Optional[Problem]: ...
    async def list_problems(self, limit: int = 100) -> List[Problem]: ...

class EvidenceStore(Protocol):
    async def save_evidence(self, evidence: Evidence) -> None: ...
    async def get_evidence(self, evidence_id: str) -> Optional[Evidence]: ...

class GraphStore(Protocol):
    async def add_edge(self, source_id: str, target_id: str, relation: str, metadata: Dict[str, Any]) -> None: ...
    async def get_neighbors(self, node_id: str, relation: Optional[str] = None) -> List[Dict[str, Any]]: ...

class IndexStore(Protocol):
    async def index_document(self, document_id: str, text: str, metadata: Dict[str, Any]) -> None: ...
    async def search(self, query: str, top_k: int = 10) -> List[Dict[str, Any]]: ...

class JobStore(Protocol):
    async def save_job(self, job_id: str, status: str, payload: Dict[str, Any]) -> None: ...
    async def get_job(self, job_id: str) -> Optional[Dict[str, Any]]: ...

class FeedbackStore(Protocol):
    async def save_feedback(self, feedback_id: str, target_type: str, target_id: str, feedback: str) -> None: ...
    async def get_feedback(self, target_id: str) -> List[Dict[str, Any]]: ...
